Statistics endpoints matei&maria
Finantele-Salbatice/proiect-colectiv-BE pull request #21
Opened 2020-11-17 19:35 UTC by MateiT

2020-11-18 14:54 UTC, renteadan commented on src/transactions/transaction.controller.ts
> +		console.log('controler');
remove console.log

2020-11-18 14:55 UTC, renteadan commented on src/transactions/transaction.controller.ts
> +	tranzactionsList(@Request() req: StatisticsRequest): Promise<any> {
it's spelled transactions, with s not zt

2020-11-18 14:55 UTC, renteadan commented on src/transactions/transaction.controller.ts
> +		console.log('controler');
remove log

2020-11-18 14:55 UTC, renteadan commented on src/transactions/transaction.gateway.ts
> +		console.log(r);
remove r= and console.log

2020-11-18 14:56 UTC, renteadan commented on src/transactions/transaction.gateway.ts
> +		console.log(r);
what is id? rename to userId. what is nr? give more suggestive naming

2020-11-18 14:56 UTC, renteadan commented on src/transactions/transaction.gateway.ts
> +	getLastTranzactions(nr: number, id: number): Promise<any> {
rename transactions

2020-11-18 14:57 UTC, renteadan commented on src/transactions/transaction.gateway.ts
> +	getLastTranzactionsSum(nr: number, id: number): Promise<any> {
rename

2020-11-18 14:57 UTC, renteadan commented on src/transactions/transaction.gateway.ts
> +		console.log('db');
remove console.log

2020-11-18 15:01 UTC, renteadan requested changes

2020-11-18 15:01 UTC, renteadan commented on src/transactions/transaction.service.ts
> +		console.log('service');
remove console log and rename function

2020-11-18 15:01 UTC, renteadan commented on src/transactions/transaction.service.ts
> +		const [result] = await this.gateway.getLastTranzactions(nr,id);
don't do [result]. this will only take the first item of the array. you need just result = ...

2020-11-18 15:01 UTC, renteadan commented on src/transactions/transaction.service.ts
> +		}
error not needed, we can just return an empty array

2020-11-18 15:01 UTC, renteadan commented on src/transactions/transaction.service.ts
> +	async lastTranzactionsAmount(nr: number, id: number): Promise<any>  {
rename params and function

2020-11-18 15:01 UTC, renteadan commented on src/transactions/transaction.service.ts
> +	async lastTranzactionsAmount(nr: number, id: number): Promise<any>  {
also we know the return type, it's not any

2020-11-18 15:01 UTC, renteadan commented on src/transactions/transaction.service.ts
> +		console.log('service2');
remove console log

2020-11-18 15:01 UTC, renteadan commented on src/transactions/transaction.service.ts
> +		}
???? you make the sum in the query, why do it again

2020-11-18 15:02 UTC, renteadan commented
the main problem is that you did not test your code! nu cred ca merge, desi voi totusi ati facut merge request. macar testati inainte

2020-11-18 18:16 UTC, MateiT commented
M-am grabit putin asa-i. Mersi de feedback

On Wed, Nov 18, 2020 at 5:02 PM renteadan <notifications@github.com> wrote:

> the main problem is that you did not test your code! nu cred ca merge,
> desi voi totusi ati facut merge request. macar testati inainte
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Finantele-Salbatice/proiect-colectiv-BE/pull/21#issuecomment-729736999>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG34Z4NM46JHXHYMMWS46NLSQPOYLANCNFSM4TZAGFXA>
> .
>

2020-11-18 22:24 UTC, MateiT reviewed
fixed

2020-11-19 07:47 UTC, renteadan requested changes

2020-11-19 07:47 UTC, renteadan commented on src/transactions/transaction.service.ts
> +		if (!result['SUM(amount)']) {
this is better. now you can write the query SELECT SUM(amount) as amount from ... and here just use result.amount

2020-11-19 07:47 UTC, renteadan commented on src/transactions/transaction.service.ts
> +		const rez = [result[0], result[1], result[2], result[3], result[4]];
this is very very very not ok. The limiting should be made from the query, not from the code. use LIMIT 5 in the query.

2020-11-19 07:47 UTC, renteadan commented on src/transactions/transaction.gateway.ts
> +		WHERE  (tr.date_time BETWEEN NOW() - INTERVAL ? DAY AND NOW()) AND (bank.user_id = ?);
you don't need () around bank.user_id. also i think it should be tr.date_time > NOW() - interval ? day. it does the same think but looks cleaner

2020-11-19 07:47 UTC, renteadan commented on src/transactions/transaction.gateway.ts
> +		SELECT SUM(amount) FROM ${this.transactionTable} as tr
another improvement you can do is use coalesce(SUM(amount), 0) as amount. Coalesce will return the first non-null value. Either the sum or 0. That way you don't have to check it again in service

2020-11-19 12:09 UTC, renteadan approved these changes

2020-11-19 12:10 UTC, merged